=== telerik/kendo-themes/packages/html-spec/schemas/component.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "kendo-html://schemas/kendo-html-spec.json",
    "title": "Schema definition for Kendo UI HTML Specification",
    "description": "The HTML specification schema for Kendo UI",
    "type": "object",
    "$definitions": {
        "component-state": { "$ref": "./component-state.schema.json#/definitions/component-state" },
        "component-option": { "$ref": "./component-option.schema.json#/definitions/component-option" },
        "component-child": { "$ref": "./component-child.schema.json#/definitions/component-child" }
    },
    "properties": {
        "title": {
            "description": "Title of the HTML spec file",
            "type": "string"
        },
        "component": {
            "description": "Name of the component",
            "type": "string"
        },
        "selector": {
            "description": "The selector/s that can target the component",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string"
            }
        },
        "states": {
            "description": "Describes the component states",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-state"
            }
        },
        "options": {
            "description": "Describes the component options",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-option"
            }
        },
        "children": {
            "description": "Describes the component children",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-child"
            }
        }
    },
    "required": [
        "$schema",
        "title",
        "component",
        "selector"
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/table/table.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Table HTML Spec",
    "component": "table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "table-head",
            "selector": [
                ".k-table-thead"
            ],
            "children": [
                {
                    "name": "table-header-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "table-header-cell",
                            "selector": [
                                ".k-table-th"
                            ],
                            "states": [
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "table-body",
            "selector": [
                ".k-table-tbody"
            ],
            "children": [
                {
                    "name": "table-body-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "states": [
                        {
                            "name": "hover",
                            "selector": [
                                ":hover",
                                ".k-hover"
                            ]
                        },
                        {
                            "name": "focus",
                            "selector": [
                                ":focus",
                                ".k-focus"
                            ]
                        },
                        {
                            "name": "selected",
                            "selector": [
                                ".k-selected"
                            ]
                        },
                        {
                            "name": "alt",
                            "selector": [
                                ".k-table-alt-row"
                            ]
                        }
                    ],
                    "children": [
                        {
                            "name": "table-body-cell",
                            "selector": [
                                ".k-table-td"
                            ],
                            "states": [
                                {
                                    "name": "hover",
                                    "selector": [
                                        ":hover",
                                        ".k-hover"
                                    ]
                                },
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                },
                                {
                                    "name": "selected",
                                    "selector": [
                                        ".k-selected"
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "table-group-row",
                    "selector": [
                        ".k-table-group-row"
                    ],
                    "children": [
                        {
                            "name": "table-group-cell",
                            "selector": [
                                ".k-table-th"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "table-footer",
            "selector": [
                ".k-table-tfoot"
            ],
            "children": [
                {
                    "name": "table-footer-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "table-footer-cell",
                            "selector": [
                                ".k-table-td"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/data-table/data-table-header.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Data Table Header HTML Spec",
    "component": "data-table-header-table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "data-table-header-table-head",
            "selector": [
                ".k-table-thead"
            ],
            "children": [
                {
                    "name": "data-table-header-table-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "data-table-header-table-cell",
                            "selector": [
                                ".k-table-th"
                            ],
                            "states": [
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/grid/grid-column-menu.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Grid Column Menu HTML Spec",
    "component": "grid-column-menu",
    "selector": [
        ".k-grid-columnmenu-popup"
    ],
    "children": [
        {
            "name": "grid-column-menu-wrap",
            "selector": [
                ".k-columnmenu-item-wrapper"
            ]
        },
        {
            "name": "grid-column-menu-item",
            "selector": [
                ".k-columnmenu-item"
            ],
            "children": [
                {
                    "name": "grid-column-menu-icon",
                    "$ref": "icon",
                    "selector": [
                        ".k-icon"
                    ]
                }
            ]
        },
        {
            "name": "grid-filter-menu-container",
            "selector": [
                ".k-filter-menu-container"
            ]
        },
        {
            "name": "grid-filter-menu-item",
            "selector": [
                ".k-multicheck-wrap .k-item"
            ]
        },
        {
            "name": "grid-filter-selected-items",
            "selector": [
                ".k-filter-selected-items"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/popup/popup.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Popup HTML Spec",
    "component": "popup",
    "selector": [
        ".k-popup"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-popup-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-popup-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-popup-lg"
                    ]
                }
            ]
        },
        {
            "name": "rounded",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-rounded-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-rounded-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-rounded-lg"
                    ]
                }
            ]
        }
    ]
}
